# SearXNG hostnames configuration
# This file references external rule files

hostnames:
  high_priority: high-priority-hosts.yml
  low_priority: low-priority-hosts.yml
  remove: remove-hosts.yml
  replace: rewrite-hosts.yml
